### ISSUE TITLE
[feature request] add option in responder mode to send NS DAD

### ISSUE THREAD

**Issue by meiser79** [Kioubit/pndpd#2]
I'd like to ask for a feature to add an option in responder mode to send NS DAD message with every NA.

My router is connected to my upstream router (from ISP). The NS coming in on eth1 (eth1 is the WAN interface on my router) are correctly answered on my router with pndpd. But it also has to send a NS DAD so that the upstream router learns the IPv6 neighbors.
I can simulate it with "ip -6 addr add xxxx:xxxx:xxxx:xxxx:ff:fe21:d123 valid_lft 1 preferred_lft 0 dev eth1".

Would it be possible to add an option "ns-dad" like
`responder {
    iface eth1
    ns-dad
}
`?
pndpd would then also send an NS packet with every NA. The NS DAD message sources an unspecified IPv6 address ::/128 and a destined solicited-node multicast address of the IPv6 address it intends to use, e.g. from the command above xxxx:xxxx:xxxx:xxxx:ff:fe21:d123.

Thanks a lot in advance!

**Comment by Kioubit** [comment]
Hi,
is this requirement specific to the router you are using as upstream? I am asking since a router would usually already learn the neighbors via the NA response and not from the NS DAD which is typically only used when a host tries to get a SLAAC address to avoid address duplication.

This feature should already be supported via the proxy mode (the recommended mode) of pndpd which proxies NDP between interfaces as the hosts would generate the NS DAD and it would then be proxied.

**Comment by meiser79** [comment]
Hi,
sorry for replying so late. I had to rethink the whole thing again. You're tight, it seems to very specific to my upstream router. I tried proxy mode, but I do not see the NS DAD from the hosts on the LAN interface of the upstream router.
But even if pndpd sent the NS DAD, it wouldn't work, because the NS DAD has to be sent for all my GUAs in the LAN before any traffic can be sent.

Thanks for your help!

**Comment by meiser79** [comment]
Hi again,

I tried again the proxy mode. The NS DAD packets are sent from my LAN clients and are received on the LAN interface of my router.
But it seems as if the NS DAD packets are converted to normal NS packets as I only see NS packets with the GUA of my WAN interface on the upstream router.
The destination address is the solicited-node multicast address of the corresponding LAN client.

**Comment by Kioubit** [comment]
The latest commit (50bf966) should fix this

**Comment by meiser79** [comment]
Thank you so much!!! This works great.

**Comment by meiser79** [comment]
One more feedback:

If I use the GUA on my internal interface on my router (eth0), the NS packets are not proxied, e.g. ping6 google.com -I <eth0 GUA>

**Comment by Kioubit** [comment]
Not sure I understand the network configuration.
What IP addresses are on the host running pndpd at eth0 (internal) and eth1(external) ?
What is the output of `ip -6 r` ?

**Comment by meiser79** [comment]
My network looks like this:
![grafik](https://user-images.githubusercontent.com/1272168/233765009-c84a6417-6c01-4acf-b0c2-6e4c62171822.png)
```

root@openwrt:~# ip -6 r
aaaa:bbbb:cccc:dddd::/64 dev eth0 proto static metric 1024 pref medium
unreachable xxxx:xxxx:cccc:dddd::/64 dev lo proto static metric 2147483647 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
fe80::/64 dev eth1 proto kernel metric 256 pref medium
default via fe80::d8ed:5157:e94:4ec0 dev eth1 proto static metric 512 pref medium
```

Both eth1 and eth0 have a GUA from the aaaa:bbbb:cccc:dddd::/64 prefix. Pinging with the eth1 GUA works, but not with the eth0 GUA.

**Comment by Kioubit** [comment]
Thanks for the detailed information.
Openwrt is using the linux kernel which means that its rules apply. Under linux, an IP address does not belong to the interface but to the host. As a result, you can assign the same GUA IP address both to eth0 and to eth1. (On eth0 as /64 and on eth1 as /128) Therefore there is no need for pndpd to answer queries for the IP address on eth1.

**Comment by Kioubit** [comment]
If you really need to keep your current configuration (which I think you can avoid), you would need to add a responder to the configuration file for the ip of eth1 (could also be done using autosense).

**Comment by meiser79** [comment]
Hi,

thanks to your feedback, I got it working with the following configuration:
```

debug off

proxy {
    ext-iface eth1
    int-iface eth0
}

responder {
    iface eth1
    autosense eth0
}
```

As I receive the IPv6 GUA via SLAAC on the wan6 interface, it's a /64. I cannot change it to /128.

**Comment by Kioubit** [comment]
Your current configuration results in pndpd sending duplicate ndp packets.
With the `autosense eth0` directive, pndpd looks at the **networks** on the interface and responds for these.
As you have a `/64` assigned on eth0, the responder block will respond for all IP addresses int the /64 which is something the proxy block is supposed to handle.
A solution is to use the `filter <address>/128` to only respond for the single IP attached to eth0 (regardless if it is assigned as /64 on eth0).

**Comment by Kioubit** [comment]
Note that assigning an IP out of the same /64 on both interfaces comes with a few limitations. (For example I don't think hosts attached to eth0 can communicate with hosts attached on eth1 but I could be wrong). Out of curiosity, what mechanism are you using to assign an IP to eth0 and is the OpenWrt router the default gateway for devices attached to eth0?

**Comment by meiser79** [comment]
Here's my OpenWrt configuration for IPv6. With 'extendprefix' enabled, OpenWrt creates an IPv6-PD out of the /64 prefix received on wan6/eth1 which can then be delegated to my clients.
I do this to have control over the propagated DNS servers (instead of relaying the RA where the upstream DNS servers are used).
The eth0/lan interface gets then an /64 out of this IPv6-PD (ip6assign command).
eth1 is "only" the upstream interface to my ISP router. All clients are routed via the OpenWrt router.

```
config interface 'wan6'
	option device '@wan'
	option proto 'dhcpv6'
	option extendprefix '1'
	option reqaddress 'try'
	option reqprefix 'auto'
	option sourcefilter '0'

config interface 'lan'
	option proto 'static'
	option device 'eth0'
	list ipaddr '192.168.1.1/24'
	option ip6assign '64'
	option ip6ifaceid 'eui64'
```

If the proxy is supposed to answer all NDP requests, why doesn't it handle the eth0 IPv6 address?
Would it be possible to add an option to the 'autosense' parameter to only handle the /128, e.g. 'interface-only'? As my IPv6 addresses are dynamic, I would otherwise need to write a script to change the config after each interface up/down.

**Comment by Kioubit** [comment]
Interesting setup
It is assumed that the router handles its own IP addresses, that's why it is not handled automatically.
Yes, I'll add the parameter over the coming days.

**Comment by meiser79** [comment]
I was able to modify the OpenWrt scripts to get a /128 as described in RFC 7278 chapter 4.3

```
--- /lib/netifd/dhcpv6.script-old
+++ /lib/netifd/dhcpv6.script
@@ -80,7 +80,12 @@
 		entry="${entry#*,}"
 		local valid="${entry%%,*}"
 
-		proto_add_ipv6_address "$addr" "$mask" "$preferred" "$valid" 1
+		# RFC 7278, chapter 4.3
+		if [ "$mask" -eq 64 -a -z "$PREFIXES" -a -n "$EXTENDPREFIX" ]; then
+			proto_add_ipv6_address "$addr" "128" "$preferred" "$valid" 1
+		else
+			proto_add_ipv6_address "$addr" "$mask" "$preferred" "$valid" 1
+		fi
 		addrsig="$addrsig $addr/$mask"
 
 		if [ -z "$RA_ADDRESSES" -a -z "$RA_ROUTES" -a \

```

I then used the ip6ifaceid option  for my eth0/lan interface to assign the EUI-64 of my eth1 interface. Now, I have the same GUA as /128 on eth1 and /64 on eth0, as you suggested.

**Comment by meiser79** [comment]
Thanks again for your great help!!! I'll close the bug report as it works now flawlessly.

**Comment by Kioubit** [comment]
Glad it works.
One more note: As a result of the documentation in the configuration file being confusingly written, the interfaces are not monitored for IP changes in your current config. I recommend using the latest commit which adds an explicit configuration option (enabled by default) to do that or waiting until the next release over the coming days which will include it.

**Comment by meiser79** [comment]
I added the change to my build. But I also added "autosense eth0" to my config as I now understood that it's for the whole /64 prefix.
